schema_version: 1

context:
  name: trivy
  version: "0.71.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/aquasecurity/${{ name }}/archive/v${{ version }}.tar.gz
    sha256: a4f4187644f6bdfba393c3c194b9ef8acc3891933c6faeeac8715a057db33785
    target_directory: src
  # csaf_distribution licenses
  - url: https://raw.githubusercontent.com/gocsaf/csaf/refs/heads/main/LICENSES/Apache-2.0.txt
    sha256: 074e6e32c86a4c0ef8b3ed25b721ca23aca83df277cd88106ef7177c354615ff
    file_name: gocsaf-LICENSE
  - url: https://raw.githubusercontent.com/xi2/xz/refs/heads/master/LICENSE
    sha256: 5c640056d513f276d56635af7a0bed81cb7eac02a31b6e56d40c416557a8d8ce
    file_name: xi2-xz-LICENSE

build:
  number: 0
  script:
    - cd src/cmd/trivy
    - if: unix
      then:
        - export GOEXPERIMENT=jsonv2
        - go build -v -o $PREFIX/bin/trivy -ldflags="-s -w"
        - cp "$(go list -m -f '{{.Dir}}' github.com/cyberphone/json-canonicalization)/LICENSE" $SRC_DIR/json-canonicalization-LICENSE
        - cp "$(go list -m -f '{{.Dir}}' github.com/in-toto/in-toto-golang)/LICENSE" $SRC_DIR/in-toto-golang-LICENSE
      else:
        - echo on
        - set GOEXPERIMENT=jsonv2
        - go build -v -o %LIBRARY_BIN%\trivy.exe -ldflags="-s"
        - for /f %%I in ('go list -m -f "{{.Dir}}" github.com/cyberphone/json-canonicalization') do copy "%%I\LICENSE" "%SRC_DIR%\json-canonicalization-LICENSE"
        - for /f %%I in ('go list -m -f "{{.Dir}}" github.com/in-toto/in-toto-golang') do copy "%%I\LICENSE" "%SRC_DIR%\in-toto-golang-LICENSE"
    - go-licenses save . --save_path ../../../licenses --ignore github.com/aquasecurity/trivy --ignore github.com/csaf-poc/csaf_distribution --ignore modernc.org/mathutil --ignore github.com/gocsaf/csaf/v3/csaf --ignore github.com/gocsaf/csaf/v3/util --ignore github.com/xi2/xz --ignore 
      github.com/cyberphone/json-canonicalization --ignore github.com/in-toto/in-toto-golang --ignore github.com/in-toto/attestation

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - trivy --help

about:
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - gocsaf-LICENSE
    - xi2-xz-LICENSE
    - in-toto-golang-LICENSE
    - json-canonicalization-LICENSE
    - licenses/
  summary: Trivy is a comprehensive and versatile security scanner. Trivy has scanners that look for security issues, and targets where it can find those issues.
  homepage: https://github.com/aquasecurity/trivy
  documentation: https://aquasecurity.github.io/trivy/

extra:
  recipe-maintainers:
    - mediocretech
    - fhoehle
    - xhochy
